sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_script:
  - npm prune
script:
  - npm test
  - npm build
deploy:
  provider: script
  script: npm run semantic-release
  on:
    branch: master
  skip_cleanup: true
