sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
deploy:
  provider: script
  script: npm run semantic-release
  on:
    branch: master
