sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_script:
  - npm prune
deploy:
  provider: script
  script: ./bin/deploy
  on:
    branch: master
